name: ROS 1 Noetic CI

on:
  push:
    branches: [ ros1-noetic ]
  pull_request:
    branches: [ ros1-noetic ]

jobs:
  ros_build_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup ROS Noetic
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install scikit-fuzzy numpy opencv-python

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros1-distro: noetic
          vcs-repo-file-url: ""
          package-selection-args: --packages-select hybrid_navigation atlas_mission_control
