name: ROS 2 CI & Publish


on:
  push:
    branches: [ main, master, ros2-development, fix/flake8-python3-unicode ]
  pull_request:
    branches: [ main, master, ros2-development, fix/flake8-python3-unicode ]


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  ros_build_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble


      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install scikit-fuzzy numpy opencv-python


      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          package-selection-args: --packages-select hybrid_navigation_msgs hybrid_navigation
          colcon-mixin-name: release
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
